CREATE TABLE Users (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Email NVARCHAR(255) NOT NULL UNIQUE,
	PasswordHash NVARCHAR(400) NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	CreatedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	UpdatedDate DATETIME2 
);