CREATE TABLE dbo.Users (
	Id	INT IDENTITY(1,1) NOT NULL,
	Email NVARCHAR(255) NOT NULL,
	PasswordHash NVARCHAR(400) NOT NULL,
	IsActive BIT NOT NULL CONSTRAINT DF_Users_IsActive DEFAULT(1),
	CreatedDate DATETIME2 NOT NULL CONSTRAINT DF_Users_CreatedDate DEFAULT (SYSUTCDATETIME()),
	UpdatedDate DATETIME2 NULL,

	CONSTRAINT PK_Users PRIMARY KEY (Id),
	CONSTRAINT UQ_Users_Email UNIQUE (Email)
);